services:
  # The PostgreSQL Database
  - type: web
    name: foodie-backend
    env: docker
    region: singapore
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: foodie-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: foodie
          property: port
      - key: DB_NAME
        fromDatabase:
          name: foodie
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: foodie
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: foodie
          property: password

databases:
  - name: foodie
    databaseName: foodie
    user: postgres
    region: singapore
    plan: free
